name         'smarchive-idea'
version      '0.2.0'
author       'Jochen Schalanda'
license      'Apache 2.0'
project_page 'https://github.com/smarchive/puppet-idea'
source       'https://github.com/smarchive/puppet-idea'
summary      'Puppet module for installing IntelliJ IDEA Community or Ultimate Edition'
description  'This module installs IntelliJ IDEA Community or Ultimate Edition from the official vendor site. Check README.md for details.'
dependency   'gini/archive', '>=0.1.0'
